---
- name: ping hosts
  gather_facts: false
  hosts: all
  tasks:
    - name: ping the hosts
      win_ping:
      register: win_ping_output

    - name: show content in registered variable
      debug: 
        var: win_ping_output
...
