---
- name: show a variable
  hosts: all
  vars_files:
    - myvars.yml
  tasks: 
    - name: show value of myvar variable
      debug:
        msg: "{{ myvar }} is the value of my variable myvar"
...